# CI to build asciidoctor spec targets

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Use Khronos container with asciidoctor toolchain preinstalled
    container: khronosgroup/docker-images:vulkan-docs-base

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # See what's there
      - name: Build spec targets
        run: |
          cd specification/2.0
          make README.html README.pdf
      - name: Archive generated files
        uses: actions/upload-artifact@v2
        with:
          name: spec-outputs
          path: |
            specification/2.0/README.html
            specification/2.0/README.pdf
